name: Metrics

on:
  push:
    branches: [main]
  schedule: [{ cron: "0 16 * * *" }]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: MBTI Personality profile
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/16personalities.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, traits
          plugin_16personalities_scores: no

      - name: Languages Used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          commits_authoring: Amanda Lima, amanda-lima, amanda.limaa0202@gmail.com
          plugin_languages_limit: 4
          delay: 120


