name: Metrics

on:
  push:
    branches: [main]
  schedule: [{ cron: "0 0 1,15 * *" }]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base_indepth: yes
          config_order: base.header, languages, topics
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          commits_authoring: Amanda Lima, amanda-lima, amanda.limaa0202@gmail.com
          plugin_languages_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: About me
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/about-me.svg
          token: NOT_NEEDED
          base: ""
          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, traits
          plugin_16personalities_scores: no
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_limit: 2



